名字: Build huggingface Image

on:
  push:
    分支: [ hug ]
    paths:
      - 'Dockerfile'
      - 'index.js'
      - 'package.json'
      - 'index.html'
  pull_request:
    分支: [ hug ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      包: write

    steps:
      - 名字: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: hug 

      - 名字: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          用户名: ${{ github.actor }}
          密码: ${{ secrets.GITHUB_TOKEN }}

      - 名字: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 名字: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          标签: |
            ghcr.io/${{ github.repository_owner }}/wujiu:latest
          标签: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=http server
            org.opencontainers.image.licenses=MIT
          cache-from: type=gha
          cache-to: type=gha,mode=max
